export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const UPDATE_PROFILE_IMG = 'UPDATE_PROFILE_IMG';
export const DELETE_PROFILE_IMG = 'DELETE_PROFILE_IMG';
export const PROFILE_IMG_LOADING = 'PROFILE_IMG_LOADING';
export const TOGGLE_USER_FOLLOW = 'TOGGLE_USER_FOLLOW';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const ALL_POSTS_LOADING = 'GET_ALL_POSTS';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const GET_FOLLOWED_USERS_POSTS = 'GET_FOLLOWED_USERS_POSTS';

export const LIKE_POST = 'LIKE_POST';
export const ADD_COMMENT = 'ADD_COMMENT';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
